# Always see the service description before init
apiVersion: v1
kind: Service
metadata:
  name: prom-dashboard
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30007
---
#See name and targetPort in service description for nodeport
#Then port-forward kubectl port-forward prometheus-grafana 3000
#admin, prom-operator
apiVersion: v1
kind: Service
metadata:
  name: grafana-dashboard
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008
---
#See name and targetPort in service description for nodeport
#Then port-forward kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443

apiVersion: v1
kind: Service
metadata:
  name: kube-dashboard
  namespace: kubernetes-dashboard
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kong
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30015
